import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/layout/Navigation';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header>
					<div>
						<Navigation className="" />
					</div>
				</header>
				{children}
				<footer className="row-start-3 flex h-[50px] flex-wrap items-center justify-center gap-4">
					<div>
						<p>footer goes here</p>
					</div>
				</footer>
			</body>
		</html>
	);
}
