import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/layout/Navigation';
import SideBar from '@/components/layout/Sidebar_Navigation';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
			>
				<header>
					<div>
						<Navigation className="invisible h-0 lg:visible lg:h-full" />
						<SideBar className="visible bg-red-700 lg:invisible lg:h-0" />
					</div>
				</header>
				<main className="h-[calc(100vh-20vh)] min-h-[calc(100vh-30vh)]">
					<div className="grid h-full grid-cols-1">
						<div className="w-[calc(95vw)] self-start justify-self-center md:w-3/4 ">
							{children}
						</div>
					</div>
				</main>
			</body>
		</html>
	);
}
